name:                bridge-practice
version:             0.1.0.0
github:              "penguinland/bridge-practice"
license:             BSD3
author:              "Alan Davidson"
maintainer:          "alan.davidson@gmail.com"
copyright:           "2019-2022 Alan Davidson"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/penguinland/bridge-practice#readme>

dependencies:
- base >= 4.11 && < 5
- containers
- MissingH
- process
- random
- transformers

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror

executables:
  bridge-practice-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bridge-practice
  server:
    main:                Main.hs
    source-dirs:         server
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bridge-practice
    - Spock
    - mtl
    - text

tests:
  bridge-practice-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bridge-practice
