name:                bridge-practice
version:             0.1.0.0
github:              "penguinland/bridge_practice"
license:             BSD3
author:              "Alan Davidson"
maintainer:          "alan.davidson@gmail.com"
copyright:           "2018-2024 Alan Davidson"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/penguinland/bridge_practice#readme>

dependencies:
- aeson
- base >= 4.11 && < 5
- containers
- extra
- MissingH
- process
- random
- template-haskell
- transformers

ghc-options:
- -Wall
- -Werror
- -j4

library:
  source-dirs: src

executables:
  server:
    main:                Main.hs
    source-dirs:         server
    ghc-options:
    - -threaded
    dependencies:
    - bridge-practice
    - mtl
    - Spock
    - text
    - wai
    - wai-extra
    - wai-middleware-static
  make_pdf:
    main:                Main.hs
    source-dirs:         make_pdf
    dependencies:
    - bridge-practice
  debugger:
    main:                Main.hs
    source-dirs:         debugger
    dependencies:
    - bridge-practice
    - ghc
  make_dealer_prog:
    main:                Main.hs
    source-dirs:         make_dealer_prog
    dependencies:
    - bridge-practice
