name: Haskell CI

on: [pull_request]

permissions:
  contents: read

jobs:
  runhaskell:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    steps:
      - name: Cache third-party libraries
        uses: actions/cache@v4
        with:
          key: ${{ matrix.os }}_${{ env.snapshot }}
          restore-keys: |
            ${{ matrix.os }}_${{ env.snapshot }}_${{ github.head_ref }}
            ${{ matrix.os }}_${{ env.snapshot }}
          path: |
            ~/.stack
            ~/.local/bin
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build project
        uses: freckle/stack-action@v5
        with:
          test: false
