name: Haskell CI

on: [pull_request]

permissions:
  contents: read

jobs:
  runhaskell:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build project
        uses: freckle/stack-action@v5
        with:
          test: false
